// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTranscriptsByServer = `-- name: CountTranscriptsByServer :one
SELECT COUNT(*) FROM transcript WHERE server_config_id = $1
`

func (q *Queries) CountTranscriptsByServer(ctx context.Context, serverConfigID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTranscriptsByServer, serverConfigID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTranscript = `-- name: CreateTranscript :one
INSERT INTO transcript (
    server_config_id, ticket_id, username, user_id,
    opened_at, closed_at, closed_by, storage_key,
    total_messages, total_attachments, total_embeds
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, server_config_id, ticket_id, username, user_id, opened_at, closed_at, closed_by, storage_key, total_messages, total_attachments, total_embeds
`

type CreateTranscriptParams struct {
	ServerConfigID  int64
	TicketID        pgtype.Text
	Username        pgtype.Text
	UserID          pgtype.Text
	OpenedAt        int64
	ClosedAt        int64
	ClosedBy        string
	StorageKey      string
	TotalMessages   pgtype.Int4
	TotalAttachments pgtype.Int4
	TotalEmbeds     pgtype.Int4
}

func (q *Queries) CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, createTranscript,
		arg.ServerConfigID,
		arg.TicketID,
		arg.Username,
		arg.UserID,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.ClosedBy,
		arg.StorageKey,
		arg.TotalMessages,
		arg.TotalAttachments,
		arg.TotalEmbeds,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.ServerConfigID,
		&i.TicketID,
		&i.Username,
		&i.UserID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.StorageKey,
		&i.TotalMessages,
		&i.TotalAttachments,
		&i.TotalEmbeds,
	)
	return i, err
}

const getAutoCloseConfig = `-- name: GetAutoCloseConfig :one
SELECT server_config_id, is_active, close_on_user_leave, close_since_open_with_no_response_mins, close_since_last_message_mins FROM auto_close_config
WHERE server_config_id = $1 LIMIT 1
`

func (q *Queries) GetAutoCloseConfig(ctx context.Context, serverConfigID int64) (AutoCloseConfig, error) {
	row := q.db.QueryRow(ctx, getAutoCloseConfig, serverConfigID)
	var i AutoCloseConfig
	err := row.Scan(
		&i.ServerConfigID,
		&i.IsActive,
		&i.CloseOnUserLeave,
		&i.CloseSinceOpenWithNoResponseMins,
		&i.CloseSinceLastMessageMins,
	)
	return i, err
}

const getTranscriptByID = `-- name: GetTranscriptByID :one
SELECT id, server_config_id, ticket_id, username, user_id, opened_at, closed_at, closed_by, storage_key, total_messages, total_attachments, total_embeds FROM transcript WHERE id = $1 AND server_config_id = $2
`

func (q *Queries) GetTranscriptByID(ctx context.Context, id int32, serverConfigID int64) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscriptByID, id, serverConfigID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.ServerConfigID,
		&i.TicketID,
		&i.Username,
		&i.UserID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.StorageKey,
		&i.TotalMessages,
		&i.TotalAttachments,
		&i.TotalEmbeds,
	)
	return i, err
}

const getTranscriptsByServer = `-- name: GetTranscriptsByServer :many
SELECT id, server_config_id, ticket_id, username, user_id,
       opened_at, closed_at, closed_by, storage_key,
       total_messages, total_attachments, total_embeds
FROM transcript
WHERE server_config_id = $1
ORDER BY closed_at DESC
LIMIT $2 OFFSET $3
`

type GetTranscriptsByServerParams struct {
	ServerConfigID int64
	Limit          int32
	Offset         int32
}

func (q *Queries) GetTranscriptsByServer(ctx context.Context, arg GetTranscriptsByServerParams) ([]Transcript, error) {
	rows, err := q.db.Query(ctx, getTranscriptsByServer, arg.ServerConfigID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transcript
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.ID,
			&i.ServerConfigID,
			&i.TicketID,
			&i.Username,
			&i.UserID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosedBy,
			&i.StorageKey,
			&i.TotalMessages,
			&i.TotalAttachments,
			&i.TotalEmbeds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerConfig = `-- name: GetServerConfig :one
SELECT id, ticket_name_style, ticket_transcript_cid, max_ticket_per_user, ticket_permissions, max_panel, max_multi_panel, authorized_member_ids, authorized_role_ids FROM server_config 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServerConfig(ctx context.Context, id int64) (ServerConfig, error) {
	row := q.db.QueryRow(ctx, getServerConfig, id)
	var i ServerConfig
	err := row.Scan(
		&i.ID,
		&i.TicketNameStyle,
		&i.TicketTranscriptCid,
		&i.MaxTicketPerUser,
		&i.TicketPermissions,
		&i.MaxPanel,
		&i.MaxMultiPanel,
		&i.AuthorizedMemberIds,
		&i.AuthorizedRoleIds,
	)
	return i, err
}

const upsertAutoCloseConfig = `-- name: UpsertAutoCloseConfig :one
INSERT INTO auto_close_config (
    server_config_id, is_active, close_on_user_leave,
    close_since_open_with_no_response_mins, close_since_last_message_mins
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (server_config_id) DO UPDATE SET
    is_active = EXCLUDED.is_active,
    close_on_user_leave = EXCLUDED.close_on_user_leave,
    close_since_open_with_no_response_mins = EXCLUDED.close_since_open_with_no_response_mins,
    close_since_last_message_mins = EXCLUDED.close_since_last_message_mins
RETURNING server_config_id, is_active, close_on_user_leave, close_since_open_with_no_response_mins, close_since_last_message_mins
`

type UpsertAutoCloseConfigParams struct {
	ServerConfigID                   int64
	IsActive                         bool
	CloseOnUserLeave                 bool
	CloseSinceOpenWithNoResponseMins int32
	CloseSinceLastMessageMins        int32
}

func (q *Queries) UpsertAutoCloseConfig(ctx context.Context, arg UpsertAutoCloseConfigParams) (AutoCloseConfig, error) {
	row := q.db.QueryRow(ctx, upsertAutoCloseConfig,
		arg.ServerConfigID,
		arg.IsActive,
		arg.CloseOnUserLeave,
		arg.CloseSinceOpenWithNoResponseMins,
		arg.CloseSinceLastMessageMins,
	)
	var i AutoCloseConfig
	err := row.Scan(
		&i.ServerConfigID,
		&i.IsActive,
		&i.CloseOnUserLeave,
		&i.CloseSinceOpenWithNoResponseMins,
		&i.CloseSinceLastMessageMins,
	)
	return i, err
}

const upsertServerConfig = `-- name: UpsertServerConfig :one
INSERT INTO server_config (
    id, ticket_name_style, ticket_transcript_cid, max_ticket_per_user, 
    ticket_permissions, max_panel, max_multi_panel, authorized_member_ids, authorized_role_ids
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    ticket_name_style = EXCLUDED.ticket_name_style,
    ticket_transcript_cid = EXCLUDED.ticket_transcript_cid,
    max_ticket_per_user = EXCLUDED.max_ticket_per_user,
    ticket_permissions = EXCLUDED.ticket_permissions,
    max_panel = EXCLUDED.max_panel,
    max_multi_panel = EXCLUDED.max_multi_panel,
    authorized_member_ids = EXCLUDED.authorized_member_ids,
    authorized_role_ids = EXCLUDED.authorized_role_ids
RETURNING id, ticket_name_style, ticket_transcript_cid, max_ticket_per_user, ticket_permissions, max_panel, max_multi_panel, authorized_member_ids, authorized_role_ids
`

type UpsertServerConfigParams struct {
	ID                  int64
	TicketNameStyle     string
	TicketTranscriptCid pgtype.Text
	MaxTicketPerUser    int32
	TicketPermissions   []byte
	MaxPanel            pgtype.Int4
	MaxMultiPanel       pgtype.Int4
	AuthorizedMemberIds []string
	AuthorizedRoleIds   []string
}

func (q *Queries) UpsertServerConfig(ctx context.Context, arg UpsertServerConfigParams) (ServerConfig, error) {
	row := q.db.QueryRow(ctx, upsertServerConfig,
		arg.ID,
		arg.TicketNameStyle,
		arg.TicketTranscriptCid,
		arg.MaxTicketPerUser,
		arg.TicketPermissions,
		arg.MaxPanel,
		arg.MaxMultiPanel,
		arg.AuthorizedMemberIds,
		arg.AuthorizedRoleIds,
	)
	var i ServerConfig
	err := row.Scan(
		&i.ID,
		&i.TicketNameStyle,
		&i.TicketTranscriptCid,
		&i.MaxTicketPerUser,
		&i.TicketPermissions,
		&i.MaxPanel,
		&i.MaxMultiPanel,
		&i.AuthorizedMemberIds,
		&i.AuthorizedRoleIds,
	)
	return i, err
}
